server:
  port: 7700

spring:
  application:
    name: investment-tracker-backend

  datasource:
    url: ${DB_URL_ENCRYPTED:OvTARXgOmx7KojZYw2hYR6Y5nr1vOgP4UFyrWFHjxxD4dOE2/enG6LwzQR5hp1j2TshWof58jWhvVFG+7IcKeBQS0dBfmgrJa8IHnQeIVw==}
    username: ${DB_USER_ENCRYPTED:jtTAI1e4q0xiOEWVH1+cR9bESZkmTapl8lL1aLL+TcsZOTPC}
    password: ${DB_PASSWORD_ENCRYPTED:Fcs1CQGLANx5Q+hekJlUp03ydXoZj8uPxjyK2R3wNLpnshXoHa1FKQ/5epmUFLyy5Gnv+xM=}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJWTTokenGeneration2024MinLength256Bits!!}
  expiration: 86400000

# Encryption Configuration (AES-256-GCM)
encryption:
  secret-key: ${ENCRYPTION_SECRET:r4d3R1yadBNWB9U3U1H5AG7OyNpA6a2sIyUWJJMPbj4=}

# Login Security
login:
  max-attempts: 3
  lock-duration-minutes: 5
  attempt-window-minutes: 5

# Logging
logging:
  level:
    com.investmenttracker: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

# SMTP Configuration (Gmail)
smtp:
  host: smtp.gmail.com
  port: 587
  username: ${SMTP_USERNAME:42mrNobody42@gmail.com}
  password: ${SMTP_PASSWORD:ybqx lxjj zjti dnlo}
  auth: true
  starttls:
    enable: true
  from: ${SMTP_USERNAME:42mrNobody42@gmail.com}
  from-name: "Investment Tracker Pro"

# Password Recovery Configuration
password-recovery:
  token-ttl-minutes: 5 # Tiempo de vida del token en minutos
  max-attempts-per-hour: 3 # Máximo de solicitudes por hora
  lock-duration-hours: 24 # Bloqueo por 24 horas
  token-length: 6 # Longitud del token numérico
